name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get update
        sudo apt-get install libcurl4-openssl-dev
        sudo apt-get install libmysqlcppconn-dev
        git clone https://github.com/Thalhammer/jwt-cpp.git
    
    - name: Build Crow
      run: |
        git clone https://github.com/CrowCpp/Crow.git
        cd Crow
        mkdir build
        cd build
        sudo apt install libasio-dev
        cmake .. -DCROW_BUILD_EXAMPLES=OFF -DCROW_BUILD_TESTS=OFF
        make install
        cd ..
    
    - name: Build Catch2
      run: |
        git clone -b v2.x https://github.com/catchorg/Catch2.git
        cd Catch2
        cmake -Bbuild -H. -DBUILD_TESTING=OFF
        sudo cmake --build build/ --target install
        cd ..

    - name: Build Project
      run: |
          make clean
          make all

    - name: Run Tests
      run: ./test
